# application-local.yml (로컬 개발용)
spring:
  config:
    activate:
      on-profile: local

  # Discord 설정
  discord:
    bot:
      token: ${DISCORD_TOKEN}  # 환경 변수로 설정
      guild-id: ${DISCORD_GUILD_ID}
      client-id: ${DISCORD_CLIENT_ID}
      enabled: true  # 봇 활성화 여부

  datasource:
    url: jdbc:h2:mem:checkus  # 인메모리 DB
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update  # 자동 스키마 생성
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: never  # ProductionDataInitializer를 사용하므로 data.sql 비활성화

  logging:
    level:
      root: DEBUG