# application-test.yml
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true

# JWT 설정 (테스트용)
jwt:
  secret: testSecretKey12345678901234567890123456789012345678901234567890
  access-token-expiration: 3600000  # 1시간
  refresh-token-expiration: 604800000  # 7일

# 로깅 설정
logging:
  level:
    saomath.checkusserver: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: DEBUG

# 테스트용 관리자 설정
app:
  admin:
    username: testadmin
    password: testpassword
    name: 테스트관리자
